title: Arrow
#-------------------------
name: Λrrow
#-------------------------
description: Functional companion to Kotlin's Standard Library
#-------------------------
author: The Λrrow Authors
keywords: functional-programming, kotlin-library, monads, monad-transformers, functional-data-structure, kotlin, fp-types, adt, free-monads, tagless-final, mtl, for-comprehension, category-theory
#-------------------------
url: https://arrow-kt.io
#-------------------------
github_repo: https://github.com/arrow-kt/arrow
#-------------------------
twitter_handle: "@arrow_kt"
#-------------------------
slack_kotlin_channel: "https://slack.kotlinlang.org"
slack_arrow_channel: "https://kotlinlang.slack.com/archives/C5UPMM0A0"
#-------------------------
sass:
    style: compressed
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', '.bundle']
#-------------------------
collections:
  code:
    output: true
# Default Front Matter values to be set
defaults:
  - scope:
      path: "apidocs/arrow-optics-mtl"
      type: "pages"
    values:
      layout: "docs-optics"
  - scope:
      path: "apidocs/arrow-optics"
      type: "pages"
    values:
      layout: "docs-optics"
  - scope:
      path: "apidocs/arrow-fx-mtl"
      type: "pages"
    values:
      layout: "docs-fx"
  - scope:
      path: "apidocs/arrow-fx-reactor"
      type: "pages"
    values:
      layout: "docs-fx"
  - scope:
      path: "apidocs/arrow-fx-rx2"
      type: "pages"
    values:
      layout: "docs-fx"
  - scope:
      path: "apidocs/arrow-fx"
      type: "pages"
    values:
      layout: "docs-fx"
  - scope:
      path: "apidocs/arrow-aql"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-mtl"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-mtl-data"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-recursion"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-recursion-data"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-generic"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-free"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-free-data"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-check"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs/arrow-check-kotlintest"
      type: "pages"
    values:
      layout: "docs-incubator"
  - scope:
      path: "apidocs"
      type: "pages"
    values:
      layout: "docs-core"
  - scope:
      type: code
    values:
      layout: code

# Plugins
plugins:
  - jekyll-redirect-from
