name: Build site

on:
  pull_request:
    paths-ignore:
    - 'README.md'

jobs:
  build_site:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Checkout orchestrator
      run: |
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow.git
        git clone https://github.com/arrow-kt/arrow.git arrow-master
    - name: "Site: run Ank"
      run: ./gradlew runAnk
    - name: "Next version: generate and validate docs for all the libraries"
      run: |
        . $BASEDIR/arrow-master/scripts/commons4gradle.sh
        for repository in $(cat $BASEDIR/arrow/lists/libs.txt); do
            cd $BASEDIR ; git clone https://github.com/arrow-kt/$repository.git; cd $repository
            addArrowDocs $BASEDIR/$repository/settings.gradle
            $BASEDIR/arrow-master/scripts/project-generate-and-validate-doc.sh $repository
        done
    - name: "Other versions: generate and validate docs"
      run: |
        . $BASEDIR/arrow-master/scripts/commons4gradle.sh
        if [ -f $BASEDIR/arrow-site/update-other-versions.txt ]; then
            for version in $(cat update-other-versions.txt); do
                echo "Update $version ..."
                SHORT_VERSION=$(echo $version | cut -d. -f1-2)
                cd $BASEDIR/arrow-site
                cp sidebar/$SHORT_VERSION/* docs/_data/
                sed -i "s/latest/$version/g" docs/_includes/_head-docs.html
                ./gradlew clean runAnk
                cd $BASEDIR/arrow
                git checkout $version
                sed -i "s/^VERSION_NAME.*/VERSION_NAME=$version/g" gradle.properties
                replaceOSSbyBintrayRepository generic-conf.gradle
                for repository in $(cat $BASEDIR/arrow/lists/libs.txt); do
                    cd $BASEDIR/$repository
                    git checkout $version
                    replaceGlobalPropertiesbyLocalConf gradle.properties
                    if [ -f arrow-docs/build.gradle ]; then
                        replaceOSSbyBintrayRepository arrow-docs/build.gradle
                    fi
                    addArrowDocs $BASEDIR/$repository/settings.gradle
                    $BASEDIR/arrow-master/scripts/project-assemble.sh $repository
                    $BASEDIR/arrow-master/scripts/project-run-dokka.sh $repository
                    $BASEDIR/arrow-master/scripts/project-run-ank.sh $repository
                    $BASEDIR/arrow-master/scripts/project-locate-doc.sh $repository
                done
            done
        fi
