name: Build site

on: pull_request

jobs:
  build_site:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Run Ank
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
      run: ./gradlew runAnk
    - name: Prepare environment
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install ruby-dev
        sudo gem install bundler --force
        sudo gem update --system
        gem --version
        echo "$( gem list | grep bundler )"
        bundle install --gemfile Gemfile --path vendor/bundle
    - name: Build site
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
        JEKYLL_ENV: production
      run: bundle exec jekyll build -s build/site -d build/_site
